// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// @ts-nocheck
import 'dotenv/config'
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env.VITE_DIRECT_URL,
  },
  migrations: {
    path: "prisma/migrations"
  },
});