// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import 'dotenv/config'
import { defineConfig } from "prisma/config";
import dotenv from "dotenv";
import 'dotenv/config';
dotenv.config();
export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: {
    url: String(process.env.VITE_DIRECT_URL) || String(process.env.DATABASE_URL),
  },
  migrations: {
    path: "prisma/migrations"
  },
});